ALTER TABLE STOCK_NOTIFICATIONS   ADD COLUMN (
  READ BOOLEAN DEFAULT FALSE,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE COMMENT_NOTIFICATIONS ADD COLUMN ( 
  READ BOOLEAN DEFAULT FALSE,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ARTICLE_NOTIFICATIONS ADD COLUMN ( 
  READ BOOLEAN DEFAULT FALSE,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE FOLLOW_NOTIFICATIONS  ADD COLUMN ( 
  READ BOOLEAN DEFAULT FALSE,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

UPDATE STOCK_NOTIFICATIONS   SET READ = FALSE;
UPDATE COMMENT_NOTIFICATIONS SET READ = FALSE;

