
ALTER TABLE COMMENT_NOTIFICATIONS ADD COLUMN (
  NOTIFY_TO_ID BIGINT
);

UPDATE COMMENT_NOTIFICATIONS SET NOTIFY_TO_ID = (
  SELECT OWNER_ID FROM ARTICLES WHERE ID = (SELECT ARTICLE_ID FROM ARTICLE_COMMENTS WHERE ID = COMMENT_NOTIFICATIONS.COMMENT_ID)
);

UPDATE COMMENT_NOTIFICATIONS SET NOTIFY_TO_ID = -1 WHERE NOTIFY_TO_ID IS NULL;

ALTER TABLE COMMENT_NOTIFICATIONS ALTER COLUMN NOTIFY_TO_ID SET NOT NULL; 

