ALTER TABLE ARTICLES ADD COLUMN (
  PUBLISHED  BOOLEAN NOT NULL DEFAULT FALSE,
  HAS_DRAFT  BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE USERS DROP COLUMN IMG_URL; 
CREATE INDEX IDX_USERS2 ON USERS (LOGIN_ID);

CREATE TABLE DRAFTS (
  ID          bigint auto_increment primary key,
  ARTICLE_ID  bigint,
  TITLE       varchar(255) NOT NULL,
  CONTENT     CLOB NOT NULL,
  OWNER_ID    bigint NOT NULL,
  CREATED     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


