CREATE TABLE UPLOADS (
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(256) NOT NULL,
    EXTENSION  VARCHAR(32),
    MIME       VARCHAR(256) NOT NULL,
    IS_IMAGE   BOOLEAN NOT NULL,
    OWNER_ID   BIGINT NOT NULL
);
CREATE INDEX IDX_UPLOADS1 ON UPLOADS (OWNER_ID);
